### ISSUE TITLE
Facing Null Pointer Exception While Setting Up OpenTelemetry with WSO2 MI 4.2.0 with Scheduled Tasks

### ISSUE THREAD

**Issue by Pranav-Codes** [wso2/product-micro-integrator#3337]
While configuring OpenTelemetry with WSO2 MI 4.2.0.79 and Jaeger, facing NullPointerException. I have deployed a Carbon Application running only the Sample Scheduled Task example available in Integration Studio. I used this documentation for OpenTelemetry configurations[1]. This configuration is working with REST APIs but not with Scheduled Tasks. The error logs are as follows:-

```
INFO {TRACE_LOGGER} - Start : Sequence <PersonRecordSeq>
ERROR {MediatorWorker} - Unexpected error executing task/async inject java.lang.NullPointerException
	at io.opentelemetry.context.Context.with(Context.java:169)
	at org.apache.synapse.aspects.flow.statistics.tracing.opentelemetry.management.handling.span.SpanHandler.startSpan(SpanHandler.java:218)
	at org.apache.synapse.aspects.flow.statistics.tracing.opentelemetry.management.handling.span.SpanHandler.startSpanOrBufferSequenceContinuationState(SpanHandler.java:167)
	at org.apache.synapse.aspects.flow.statistics.tracing.opentelemetry.management.handling.span.SpanHandler.handleOpenEntryEvent(SpanHandler.java:131)
	at org.apache.synapse.aspects.flow.statistics.collectors.OpenEventCollector.reportEntryEvent(OpenEventCollector.java:112)
	at org.apache.synapse.mediators.base.SequenceMediator.reportOpenStatistics(SequenceMediator.java:486)
	at org.apache.synapse.mediators.base.SequenceMediator.mediate(SequenceMediator.java:126)
	at org.apache.synapse.mediators.MediatorWorker.run(MediatorWorker.java:89)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

Exception in thread "SynapseWorker-1" java.lang.NullPointerException
	at org.apache.synapse.FaultHandler.handleFault(FaultHandler.java:85)
	at org.apache.synapse.mediators.MediatorWorker.run(MediatorWorker.java:110)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

[1] <a href="https://mi.docs.wso2.com/en/latest/observe-and-manage/classic-observability-traces/monitoring-with-opentelemetry-mi/">https://mi.docs.wso2.com/en/latest/observe-and-manage/classic-observability-traces/monitoring-with-opentelemetry-mi/</a>

**Comment by cnapagoda** [comment]
Isn't this already addressed with #3302 ?

**Comment by Pranav-Codes** [comment]
> Isn't this already addressed with #3302 ?

That was for an erroneous Scheduled Task. I used a working Sample Scheduled Task from Integration Studio that does not throw error without OpenTelemetry configuration.

**Comment by manuranga** [comment]
I am seeing somthing similer in MI 4.3.0
```
Exception in thread "SynapseWorker-25" java.lang.NullPointerException: Cannot invoke "io.opentelemetry.context.ImplicitContextKeyed.storeInContext(io.opentelemetry.context.Context)" because "value" is null
	at io.opentelemetry.context.Context.with(Context.java:169)
	at org.apache.synapse.aspects.flow.statistics.tracing.opentelemetry.management.handling.span.SpanHandler.startSpan(SpanHandler.java:218)
	at org.apache.synapse.aspects.flow.statistics.tracing.opentelemetry.management.handling.span.SpanHandler.startSpanOrBufferSequenceContinuationState(SpanHandler.java:167)
	at org.apache.synapse.aspects.flow.statistics.tracing.opentelemetry.management.handling.span.SpanHandler.handleOpenEntryEvent(SpanHandler.java:131)
	at org.apache.synapse.aspects.flow.statistics.collectors.OpenEventCollector.reportEntryEvent(OpenEventCollector.java:112)
	at org.apache.synapse.mediators.base.SequenceMediator.reportOpenStatistics(SequenceMediator.java:486)
	at org.apache.synapse.mediators.base.SequenceMediator.mediate(SequenceMediator.java:126)
	at org.apache.synapse.mediators.MediatorFaultHandler.onFault(MediatorFaultHandler.java:96)
	at org.apache.synapse.FaultHandler.handleFault(FaultHandler.java:114)
	at org.apache.synapse.mediators.MediatorWorker.run(MediatorWorker.java:110)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)

```
