### ISSUE TITLE
[Bug]: Nullpointer Exception when calling Inbound EPs

### ISSUE THREAD

**Issue by dilshanfardil** [wso2/product-micro-integrator#3481]
### Description

Hi Team,

### Description

We are getting this ERROR on the startup in the Kubernetes environment

```
[2024-07-30 07:57:50,730] ERROR {InboundHttpServerWorker} - Exception occurred when running org.wso2.carbon.inbound.endpoint.protocol.http.InboundHttpServerWorker java.lang.NullPointerException
    at org.wso2.micro.integrator.transport.handlers.AbstractHttpGetRequestProcessor.getServicePath(AbstractHttpGetRequestProcessor.java:225)
    at org.wso2.micro.integrator.transport.handlers.PassThroughNHttpGetProcessor.process(PassThroughNHttpGetProcessor.java:164)
    at org.apache.synapse.transport.passthru.ServerWorker.processHttpRequestUri(ServerWorker.java:808)
    at org.wso2.carbon.inbound.endpoint.protocol.http.InboundHttpServerWorker.run(InboundHttpServerWorker.java:103)
    at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.base/java.lang.Thread.run(Thread.java:829)

```

### Steps to Reproduce

1.  Change the property -DNonUserCoreMode to false [1] since customer is using secondary user stores
2. Run this script. This script has the /liveness api calling after opening the inbound ep port. [run_curl_every_5_seconds.txt](https://github.com/user-attachments/files/16498864/run_curl_every_5_seconds.txt) change this to sh
3. You will see the Null-pointer in the carbon logs.

**Comment by AmilaSamith** [comment]
Public Fix : https://github.com/wso2/product-micro-integrator/pull/3586
