### ISSUE TITLE
IndexOutOfBoundsException happens when deploying multiple DSS

### ISSUE THREAD

**Issue by dilshanfardil** [wso2/product-micro-integrator#3781]
### Description

We are getting this ERROR while deploying two CAPPS with DSS

```
Current Params: {lastName=Smith, firstName=John, zipCode=10001, memberClubCode=AB007, memberNumber=MEM123, phoneNumber=123-456-7890}
Current Request Name: _getmember_search
Nested Exception:-
java.lang.ArrayIndexOutOfBoundsException: 2
Source Data Service:-
Name: memberDataService
Location: /Users/imedya/Desktop/TICKETS/wso2mi-4.1.0/tmp/carbonapps/-1234/1732120920794aaaDSSProjectCompositeExporter_1.0.0-SNAPSHOT.car/memberDataService_1.0.0/memberDataService-1.0.0.dbs
Description:
Default Namespace: http://ws.wso2.org/dataservice
DS Code: DATABASE_ERROR

	at org.wso2.micro.integrator.dataservices.core.description.query.SQLQuery.processPreStoredProcQuery(SQLQuery.java:966)
	at org.wso2.micro.integrator.dataservices.core.description.query.SQLQuery.runPreQuery(SQLQuery.java:2336)
	at org.wso2.micro.integrator.dataservices.core.description.query.Query.execute(Query.java:301)
	at org.wso2.micro.integrator.dataservices.core.engine.CallQuery.executeElement(CallQuery.java:285)
	at org.wso2.micro.integrator.dataservices.core.engine.OutputElement.execute(OutputElement.java:88)
	at org.wso2.micro.integrator.dataservices.core.description.resource.Resource.execute(Resource.java:66)
	at org.wso2.micro.integrator.dataservices.core.engine.DataService.invoke(DataService.java:613)
	at org.wso2.micro.integrator.dataservices.core.engine.DSOMDataSource.execute(DSOMDataSource.java:94)
	... 13 more
Caused by: java.lang.ArrayIndexOutOfBoundsException: 2
	at org.wso2.micro.integrator.dataservices.core.description.query.SQLQuery.generateSQLupdateQuery(SQLQuery.java:1583)
	at org.wso2.micro.integrator.dataservices.core.description.query.SQLQuery.createProcessedPreparedStatement(SQLQuery.java:1405)
	at org.wso2.micro.integrator.dataservices.core.description.query.SQLQuery.processPreStoredProcQuery(SQLQuery.java:924)
	... 20 more

```

### Steps to Reproduce

1. Deploy the DSS with SP.
2. Deploy the DSS with UPDATE Query.
3. Try to invoke the memberDataService, SearchMemberships query.

### Version

4.1.0

**Comment by GDLMadushanka** [comment]
fixed via https://github.com/wso2/product-micro-integrator/pull/3149
