### ISSUE TITLE
Unit test occurs error due to Kafka Connector

### ISSUE THREAD

**Issue by a0529gox** [wso2/product-micro-integrator#3852]
### Description

Unit test server does not recognize `kafkaTransport` tag.
After removing the resource contains `kafkaTransport`, unit test was running well.

unit test command
```sh
mvn install -DtestServerType=remote -DtestServerHost=localhost -DtestServerPort=9008 -P test
```

APIs:
```xml
    <resource methods="POST" uri-template="/KafkaConnection">
        <inSequence>
            <kafkaTransport.publishMessages configKey="MyKafkaConnector">
                <keySchemaSoftDeleted>false</keySchemaSoftDeleted>
                <valueSchemaSoftDeleted>false</valueSchemaSoftDeleted>
                <topic>wso2mi</topic>
                <partitionNo>0</partitionNo>
            </kafkaTransport.publishMessages>
            <payloadFactory media-type="json" template-type="default">
                <format>
                    {"message":"done"}</format>
                <args>
                </args>
            </payloadFactory>
            <respond />
        </inSequence>
        <faultSequence>
        </faultSequence>
    </resource>
```

unit test server logs:
```log
[2024-12-30 08:22:36,951] ERROR {APIDeployer} - API deployment from the file : MyProject : Failed. org.apache.synapse.SynapseException: Unknown mediator referenced by configuration element : {http://ws.apache.org/ns/synapse}kafkaTransport
	at org.apache.synapse.config.xml.MediatorFactoryFinder.getMediator(MediatorFactoryFinder.java:246)
	at org.apache.synapse.config.xml.AbstractListMediatorFactory.addChildren(AbstractListMediatorFactory.java:53)
	at org.apache.synapse.config.xml.SequenceMediatorFactory.createAnonymousSequence(SequenceMediatorFactory.java:70)
	at org.apache.synapse.config.xml.rest.ResourceFactory.configureSequences(ResourceFactory.java:109)
	at org.apache.synapse.config.xml.rest.ResourceFactory.createResource(ResourceFactory.java:51)
	at org.apache.synapse.config.xml.rest.APIFactory.createAPI(APIFactory.java:98)
	at org.apache.synapse.deployers.APIDeployer.deploySynapseArtifact(APIDeployer.java:49)
	at org.apache.synapse.unittest.ConfigurationDeployer.deployApiArtifact(ConfigurationDeployer.java:117)
	at org.apache.synapse.unittest.TestingAgent.processTestArtifact(TestingAgent.java:134)
	at org.apache.synapse.unittest.RequestHandler.runTestingAgent(RequestHandler.java:199)
	at org.apache.synapse.unittest.RequestHandler.run(RequestHandler.java:83)
```

### Steps to Reproduce

N/A

### Version

4.3.0

**Comment by a0529gox** [comment]
According to this [document](https://mi.docs.wso2.com/en/latest/develop/creating-artifacts/adding-connectors/).
The problem was solved after adding the xml file `{org.wso2.carbon.connector}kafkaTransport.xml` in the `MI_HOME/repository/deployment/server/synapse-configs/default/imports`

```yaml
<import xmlns="http://ws.apache.org/ns/synapse"
        name="kafkaTransport"
        package="org.wso2.carbon.connector"
        status="enabled"/>
```
